# Use the official Node.js image as a base image
FROM node:16-slim

# Set the working directory inside the container
WORKDIR /usr/src/app/client

# Copy client package.json and package-lock.json to the working directory
COPY client/package*.json ./

# Install the client dependencies
RUN npm install

# Copy the rest of the client code to the working directory
COPY client/ .

# Expose the port your client will use
EXPOSE 3000

# Command to run your client
CMD ["npm", "start"]
