# Use the official Node.js image as a base image
FROM node:16-slim

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the server dependencies
RUN npm install

# Copy the rest of the server code to the working directory
COPY . .

# Expose the port your server will use
EXPOSE 8080

# Command to run your server
CMD ["npm", "run", "server"]
