apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: darshi666/client:latest
        ports:
        - containerPort: 3000